fail_fast: true
repos:
    - repo: local
      hooks:
          - id: ruff
            name: ruff check
            language: system
            require_serial: true
            types: [python]
            entry: uv run ruff check
            args:
                - --fix
                - --exit-non-zero-on-fix
          - id: ruff-format
            name: ruff format
            language: system
            require_serial: true
            types: [python]
            entry: uv run ruff format
            args:
                - --verbose
