name: Ruff
on: [push, pull_request]
jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/ruff-action@v3
            # Also check formatting
            - run: ruff format --diff
